# Generated by Django 5.2 on 2025-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mini_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
