# Generated by Django 5.2 on 2025-08-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleteprofile',
            options={'verbose_name': 'Delete Profile', 'verbose_name_plural': 'Delete Profiles'},
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='deleteprofile',
            name='updated_at',
        ),
    ]
