# Generated by Django 5.2 on 2025-07-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mini_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('JINSI', 'Jinsi'), ('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], default='JINSI', max_length=10, null=True),
        ),
    ]
