# Generated by Django 5.2 on 2025-07-28 06:43

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_username', models.CharField(blank=True, max_length=150, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
