# Generated by Django 5.2 on 2025-09-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode_delete_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='expires_at',
        ),
    ]
